#!/usr/bin/env python3
"""One-time migration utility for Atlas key vault data into a Docker named volume.

What it migrates:
- *.enc files
- index.json

What it does with masker/master key:
- Reads masker.key (or master.key) from the source folder
- Converts it to hex and writes MASTER_ENCRYPTION_KEY into an env file
- Does NOT copy masker/master key into the Docker volume
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess


def run(command: list[str]) -> None:
    completed = subprocess.run(command, text=True)
    if completed.returncode != 0:
        raise SystemExit(completed.returncode)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate encrypted SSH key vault into Docker volume")
    parser.add_argument(
        "--source",
        default="./keys",
        help="Path to existing key vault directory (default: ./keys)",
    )
    parser.add_argument(
        "--volume",
        default="ssh_key_data",
        help="Docker named volume to receive key vault files (default: ssh_key_data)",
    )
    parser.add_argument(
        "--env-output",
        default=".env.docker",
        help="Path to write MASTER_ENCRYPTION_KEY (default: .env.docker)",
    )
    return parser.parse_args()


def find_master_key_file(source_dir: pathlib.Path) -> pathlib.Path:
    for name in ("masker.key", "master.key"):
        candidate = source_dir / name
        if candidate.is_file():
            return candidate
    raise FileNotFoundError("Expected masker.key or master.key in source directory")


def main() -> None:
    args = parse_args()
    source_dir = pathlib.Path(args.source).expanduser().resolve()

    if not source_dir.exists() or not source_dir.is_dir():
        raise SystemExit(f"Source directory does not exist: {source_dir}")

    index_file = source_dir / "index.json"
    if not index_file.is_file():
        raise SystemExit(f"Missing required file: {index_file}")

    enc_files = list(source_dir.glob("*.enc"))
    if not enc_files:
        raise SystemExit(f"No .enc files found in {source_dir}")

    master_file = find_master_key_file(source_dir)
    master_key = master_file.read_bytes()
    if len(master_key) != 32:
        raise SystemExit(
            f"Invalid key length in {master_file}: got {len(master_key)} bytes, expected 32"
        )

    env_path = pathlib.Path(args.env_output).expanduser().resolve()
    env_path.write_text(
        "# Generated by scripts/migrate_key_vault.py\n"
        "# Keep this file secret and never commit it\n"
        f"MASTER_ENCRYPTION_KEY={master_key.hex()}\n",
        encoding="utf-8",
    )

    run(["docker", "volume", "create", args.volume])

    copy_command = [
        "docker",
        "run",
        "--rm",
        "-v",
        f"{args.volume}:/to",
        "-v",
        f"{source_dir}:/from:ro",
        "alpine:3.21",
        "sh",
        "-c",
        (
            "set -eu; "
            "mkdir -p /to; "
            "cp -a /from/*.enc /to/; "
            "cp -a /from/index.json /to/; "
            "chmod 700 /to; "
            "chmod 600 /to/*.enc /to/index.json"
        ),
    ]
    run(copy_command)

    print("Migration complete.")
    print(f"- Docker volume: {args.volume}")
    print(f"- Migrated files: {len(enc_files)} .enc file(s) + index.json")
    print(f"- Wrote MASTER_ENCRYPTION_KEY to: {env_path}")
    print("- masker.key/master.key intentionally NOT copied into Docker volume")


if __name__ == "__main__":
    try:
        main()
    except FileNotFoundError as error:
        raise SystemExit(str(error)) from error
